model:
  arch: unetplusplus
  in_channels: 3
  out_channels: 1
  model_args:
    encoder_name: resnet34
    encoder_weights: imagenet
training:
  train_dataset_path: /root/MaskGenerator/Datasets/train/simu_v0
  eval_dataset_path: /root/MaskGenerator/Datasets/test/MoLane
  seed: 42
  batch_size: 32
  num_epochs: 100
  lr: 0.001
  step_size: 10
  gamma: 0.1
  patience: 30
  delta: 0.0
  train_image_size:
  - 256
  - 256
  augmentations:
  - geometry
  - dropout
  - color_invariance
  - color_variation
  - blur
  - noise
  - weather
  use_amp: false
  qat:
    enabled: false
    backend: fbgemm
  loss:
  - name: bce
    weight: 0.5
    params:
      pos_weight: true
  - name: dice
    weight: 0.5
    params:
      smooth: 1.0
other:
  name: 20250617_023025_e53ea2dd94
  run_hash: e53ea2dd94
  run_dir: /root/MaskGenerator/experiments/20250617_023025_e53ea2dd94
  git_commit: 3778dff9be3b6370065310863c81861a2d80fa2b
  verbose: false
